ALTER TABLE transactions ADD COLUMN IF NOT EXISTS txn_id VARCHAR(64) DEFAULT NULL;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS description VARCHAR(255) DEFAULT NULL;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS utr VARCHAR(190) DEFAULT NULL;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS collection_mode VARCHAR(32) DEFAULT NULL;
UPDATE transactions SET txn_id=transaction_id WHERE txn_id IS NULL AND transaction_id IS NOT NULL;
