<?php
declare(strict_types=1);

class SimpleAgreementPdf
{
    private string $content = '';
    private array $pages = [];

    public function addPage(): void
    {
        if ($this->content !== '') {
            $this->pages[] = $this->content;
        }
        $this->content = '';
    }

    public function text(float $x, float $y, string $text, int $size = 10, bool $bold = false): void
    {
        $font = $bold ? '/F2' : '/F1';
        $escaped = str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], mb_substr($text, 0, 200));
        $this->content .= "BT {$font} {$size} Tf {$x} {$y} Td ({$escaped}) Tj ET\n";
    }

    public function wrapText(float $x, float $startY, string $text, int $size = 9, float $lineHeight = 13, float $maxWidth = 495): float
    {
        $words = preg_split('/\s+/', trim(strip_tags($text))) ?: [];
        $line = '';
        $y = $startY;
        foreach ($words as $word) {
            $candidate = $line === '' ? $word : $line . ' ' . $word;
            if (strlen($candidate) * ($size * 0.45) > $maxWidth && $line !== '') {
                $this->text($x, $y, $line, $size);
                $y -= $lineHeight;
                $line = $word;
            } else {
                $line = $candidate;
            }
            if ($y < 60) {
                $this->addPage();
                $y = 800;
            }
        }
        if ($line !== '') {
            $this->text($x, $y, $line, $size);
            $y -= $lineHeight;
        }
        return $y;
    }

    public function generate(array $meta, array $sections): string
    {
        $this->text(50, 800, COMPANY_LEGAL_NAME, 14, true);
        $this->text(50, 785, 'Merchant Services Agreement — Acceptance Record', 11, true);
        $this->text(50, 768, 'Version ' . ($meta['version'] ?? '') . ' · Audit UWA-' . ($meta['acceptance_id'] ?? ''), 8);
        $y = 745;
        foreach ([
            'Merchant' => $meta['legal_name'] ?? '',
            'Merchant ID' => $meta['merchant_code'] ?? '',
            'Authorized signatory (typed)' => $meta['signature_name'] ?? '',
            'Accepted at (IST)' => $meta['accepted_at'] ?? '',
            'IP address' => $meta['accepted_ip'] ?? '',
            'Document fingerprint' => $meta['document_hash'] ?? '',
        ] as $label => $value) {
            $this->text(50, $y, $label . ': ' . $value, 9);
            $y -= 14;
        }
        $y -= 8;
        $this->text(50, $y, 'Agreement clauses accepted electronically:', 10, true);
        $y -= 18;
        foreach ($sections as $section) {
            $title = (string)($section[0] ?? 'Section');
            $body = (string)($section[1] ?? '');
            $this->text(50, $y, $title, 9, true);
            $y -= 14;
            $y = $this->wrapText(58, $y, $body, 8, 12);
            $y -= 6;
            if ($y < 80) {
                $this->addPage();
                $y = 800;
            }
        }
        $this->addPage();
        $this->text(50, 780, 'This PDF is a compliance record generated by UniWeb.', 8);
        $this->text(50, 766, 'Full agreement: ' . APP_URL . '/business_agreement.php', 8);
        return $this->buildPdf();
    }

    private function buildPdf(): string
    {
        if ($this->content !== '') {
            $this->pages[] = $this->content;
            $this->content = '';
        }
        if ($this->pages === []) {
            $this->pages[] = '';
        }
        $objects = [];
        $pageObjNums = [];
        $next = 3;
        $objects[1] = "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n";
        foreach ($this->pages as $i => $pageContent) {
            $pageObjNums[] = $next;
            $contentObj = $next + 1;
            $objects[$next] = "{$next} 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents {$contentObj} 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >> endobj\n";
            $objects[$contentObj] = "{$contentObj} 0 obj << /Length " . strlen($pageContent) . " >> stream\n" . $pageContent . "endstream endobj\n";
            $next += 2;
        }
        $kids = implode(' ', array_map(static fn(int $n): string => "{$n} 0 R", $pageObjNums));
        $objects[2] = "2 0 obj << /Type /Pages /Kids [{$kids}] /Count " . count($pageObjNums) . " >> endobj\n";
        $objects[5] = "5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n";
        $objects[6] = "6 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj\n";
        ksort($objects);
        $pdf = "%PDF-1.4\n";
        $offsets = [0];
        foreach ($objects as $obj) {
            $offsets[] = strlen($pdf);
            $pdf .= $obj;
        }
        $xref = strlen($pdf);
        $pdf .= "xref\n0 " . count($offsets) . "\n";
        $pdf .= "0000000000 65535 f \n";
        for ($i = 1; $i < count($offsets); $i++) {
            $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
        }
        $pdf .= "trailer << /Size " . count($offsets) . " /Root 1 0 R >>\nstartxref\n{$xref}\n%%EOF";
        return $pdf;
    }
}
