<?php
/**
 * Structured findings for Deep A–Z Audit PDF (English).
 * Each item: id, title, problem, expectation, solution
 */
declare(strict_types=1);

return [
    [
        'title' => '0 · Executive summary & how to use',
        'intro' => 'This report is evidence-based from the uniweb1 codebase (nav, search, panels, public pages, Phase 11 parks). It is not a live browser crawl of every Hostinger URL. Owner should verify Priority fixes on live after Git pull. Work top-down: wiring and search first; market/white-label are reference.',
        'items' => [
            [
                'id' => 'SUM-01',
                'title' => 'What is healthy already',
                'problem' => 'Without a baseline, every gap looks like a blocker.',
                'expectation' => 'Know what already works so effort goes to real gaps.',
                'solution' => 'Keep: merchant/admin/staff nav file targets exist; NBFC and customer PPI wallet stay out of menus; Video KYC is live camera (not upload-only); Partner Registry as keys plane; payment links Fixed+Open; Instant Test Pay in Test Mode; Watchdog/cron pattern; customer portal = pay + complaints only.',
            ],
            [
                'id' => 'SUM-02',
                'title' => 'Top priority action list',
                'problem' => 'Too many findings can freeze progress.',
                'expectation' => 'A short ordered list for the next engineering week.',
                'solution' => 'P1: Global search coverage + admin Payment Links/QR in nav+search. P2: Fix abortFeatureDisabled redirect; remove duplicate Watchdog nav; soft PDF/KYC die pages. P3: Merge reports/monitor UX; pci.php alias; public copy wallet wording. P4: Owner live smoke + migrations Apply. Park: live Route, NBFC, PPI.',
            ],
            [
                'id' => 'SUM-03',
                'title' => 'Doable vs not doable (product)',
                'problem' => 'Requests for NBFC/PPI/Route look like missing features but are Owner parks.',
                'expectation' => 'Clear DOABLE now vs NEVER / PARKED.',
                'solution' => 'DOABLE: search expansion, nav cleanup, empty states, PCI alias, soft errors, pack regenerate, KYC queue, partner keys paste. PARKED/NEVER: live Route SDK, NBFC lending, customer PPI wallet, fake RBI PA claims, dropping production DB.',
            ],
        ],
    ],
    [
        'title' => '1 · Technical errors, bugs & wiring',
        'intro' => 'Broken wiring, white screens, dead links, wrong redirects.',
        'items' => [
            [
                'id' => 'TECH-01',
                'title' => 'NBFC disabled redirect can land on public home',
                'problem' => 'abortFeatureDisabled() checks isMerchantLoggedIn() which does not exist in repo (isLoggedIn() does). Logged-in users hitting hidden NBFC URLs may be sent to index.php or a bare 403 exit.',
                'expectation' => 'Merchant → dashboard.php; staff/admin → staff/admin dashboard; clear flash. Never bare white exit for logged-in users.',
                'solution' => 'Fix includes/ops_security.php abortFeatureDisabled() to use isLoggedIn()/isAdminLoggedIn(); replace bare exit with flash+redirect.',
            ],
            [
                'id' => 'TECH-02',
                'title' => 'PDF / KYC document bare die() white ends',
                'problem' => 'invoice_pdf.php, merchant_agreement_pdf.php, admin_kyc_doc.php still die/exit with plain text on missing docs.',
                'expectation' => 'Minimal branded HTML error with Back link (same pattern as checkout unavailable).',
                'solution' => 'Replace die/exit with a small error template or flash+redirect when a session exists.',
            ],
            [
                'id' => 'TECH-03',
                'title' => 'Some merchant pages redirect to login without flash',
                'problem' => 'merchant_launch.php, merchant_setup.php and similar call redirect(login) without always flashing why.',
                'expectation' => 'User always sees Please log in or session expired.',
                'solution' => 'Use requireLogin() everywhere or flash before redirect.',
            ],
            [
                'id' => 'TECH-04',
                'title' => 'pci.php missing (pci_dss.php is real page)',
                'problem' => 'Footer correctly links pci_dss.php; /pci.php does not exist → 404 for old bookmarks.',
                'expectation' => '/pci or pci.php reaches the PCI statement.',
                'solution' => 'Add thin pci.php redirect to pci_dss.php (same pattern as cust.php).',
            ],
            [
                'id' => 'TECH-05',
                'title' => 'Admin Watchdog listed twice in Advanced nav',
                'problem' => 'admin_watchdog.php and admin_link_audit.php both appear; the second only redirects to Watchdog rules tab.',
                'expectation' => 'One nav entry for Link Watchdog.',
                'solution' => 'Remove admin_link_audit.php from sidebar; keep redirect file for old bookmarks.',
            ],
            [
                'id' => 'TECH-06',
                'title' => 'Video KYC appears as its own nav page but only redirects',
                'problem' => 'video_kyc.php only redirects to kyc.php?section=video while still listed in merchant nav.',
                'expectation' => 'One KYC entry; video section inside KYC.',
                'solution' => 'Remove video_kyc.php from sidebar; link KYC → video section. Keep alias files.',
            ],
            [
                'id' => 'TECH-07',
                'title' => 'Live config include drift (partially mitigated)',
                'problem' => 'Live Hostinger config.php uses a short require_once list; many helpers were missing until cloud_modules bridge.',
                'expectation' => 'All runtime includes load without overwriting DB/ENCRYPTION secrets.',
                'solution' => 'Git pull so cloud_modules.php loads missing modules. Optional later: sync only $__includes; never paste full config.dev over live config.',
            ],
            [
                'id' => 'TECH-08',
                'title' => 'Cron Forbidden die is OK for machines',
                'problem' => 'Cron scripts exit Forbidden when hit without key — looks like white text if opened in browser.',
                'expectation' => 'Humans use admin Watchdog UI; crons stay machine-only.',
                'solution' => 'Keep cron die; do not add crons to sidebar. Document in ops runbook.',
            ],
            [
                'id' => 'TECH-09',
                'title' => 'Payment Pack old links could 404/error',
                'problem' => 'Expired or inactive pack URLs opened Error tabs for Demo Store.',
                'expectation' => 'Pack shows only active Fixed+Open links; regenerate retires old ones.',
                'solution' => 'Already fixed in code (027c3f9): regenerate Fixed+Open, inactive old pack. Owner: Git pull + Regenerate Pack on live.',
            ],
            [
                'id' => 'TECH-10',
                'title' => 'Payment Links method dropdown empty (partner filter)',
                'problem' => 'get_available_pay_methods filtered Direct UPI via gateway_registry/partner_methods so only All enabled methods showed.',
                'expectation' => 'Entitled methods (at least UPI P2M) always selectable in Test Mode.',
                'solution' => 'Already fixed (7beb1b2). Owner hard-refresh Payment Links after pull.',
            ],
        ],
    ],
    [
        'title' => '2 · Design, menus & page structure',
        'intro' => 'Where menus and pages should sit for a professional PA/PG console.',
        'items' => [
            [
                'id' => 'IA-01',
                'title' => 'Homepage should sell Collect first',
                'problem' => 'If the hero is generic fintech noise or over-claims (instant settle, white-label buy, Route live), serious merchants bounce.',
                'expectation' => 'Hero: collect via UPI/QR/links/checkout; Test free; Live after KYC. Two CTAs. Trust strip. No NBFC/PPI/Route as available products.',
                'solution' => 'Tighten index.php to Collect / Operate / Settle; link Trust, Status, API docs; keep compare.php honest.',
            ],
            [
                'id' => 'IA-02',
                'title' => 'Admin Advanced is too dense',
                'problem' => '~40 Advanced items bury daily tools.',
                'expectation' => 'Daily path short; advanced tools findable via search + subgroups.',
                'solution' => 'Keep collapse; subgroup Risk / Money / Ops / Security; fix search so Advanced pages are jumpable by nickname.',
            ],
            [
                'id' => 'IA-03',
                'title' => 'Admin Payment Links & QR Codes missing from sidebar',
                'problem' => 'admin_payment_links.php and admin_qr_codes.php exist and staff can open them, but they are not in admin/staff nav.',
                'expectation' => 'Ops pages used daily appear in nav and search.',
                'solution' => 'Add both to uniwebAdminNavGroups and staffNavForRole for finance/ops/ceo/super.',
            ],
            [
                'id' => 'IA-04',
                'title' => 'Merchant Collect group is correct',
                'problem' => 'None critical — Payment Links, QR, Instant UPI QR, Payment Methods map to collect.',
                'expectation' => 'Collect tools stay together; Instant UPI QR must warn money may bypass UniWeb ledger.',
                'solution' => 'Keep group; strengthen Instant UPI QR banner copy.',
            ],
            [
                'id' => 'IA-05',
                'title' => 'wallet.php naming vs PPI fear',
                'problem' => 'Word wallet confuses buyers who fear consumer PPI.',
                'expectation' => 'Merchant settlement balance language only.',
                'solution' => 'Keep page; prefer nav label Settlement Balance; solutions.php copy Settlements & wallet → Settlements & balance.',
            ],
            [
                'id' => 'IA-06',
                'title' => 'Staff vs merchant Team labels',
                'problem' => 'Team/staff words collide across merchant_team and admin_manage_staff.',
                'expectation' => 'Merchant: Team members. Admin: Employees / Staff.',
                'solution' => 'Copy-only rename in UI strings; do not merge files.',
            ],
        ],
    ],
    [
        'title' => '3 · Panels A–Z (Admin, Merchant, Sub-merchant, Staff, Team, Customer)',
        'items' => [
            [
                'id' => 'PNL-A01',
                'title' => 'Admin panel — keys only in Partner Registry',
                'problem' => 'Historical dual key UIs confuse ops (platform paste vs Registry).',
                'expectation' => 'Live secrets only on Partner Detail → Keys; Platform Settings = SMTP/cron/templates.',
                'solution' => 'Keep Phase 1 rule; Owner never pastes partner keys into wrong screen.',
            ],
            [
                'id' => 'PNL-A02',
                'title' => 'Admin KYC queue must show decrypted PII',
                'problem' => 'Ciphertext on KYC review blocks ops (Cleanup Block B).',
                'expectation' => 'Admin sees real PAN/GST after decrypt; DB stays encrypted.',
                'solution' => 'Already shipped sensitiveUiPlain / decryptMerchantPiiFields. Owner: pull + migration 062 + Encrypt PII backfill if needed.',
            ],
            [
                'id' => 'PNL-M01',
                'title' => 'Merchant panel — Fixed and Open payment links',
                'problem' => 'Merchants need both preset amount and customer-entered amount.',
                'expectation' => 'Create Fixed or Open on Payment Links; Pack offers both per method.',
                'solution' => 'Shipped. Owner regenerate pack on live after pull.',
            ],
            [
                'id' => 'PNL-M02',
                'title' => 'Merchant Instant Settlement honesty',
                'problem' => 'UI exists but live bank transfer needs partner keys.',
                'expectation' => 'Never look like live payout without rails.',
                'solution' => 'Keep waiting/partner messaging; do not market instant forever.',
            ],
            [
                'id' => 'PNL-SM01',
                'title' => 'Sub-merchant / Agents vs Team',
                'problem' => 'agents.php (child merchants), merchant_team.php (portal users), admin_sub_merchants.php (hierarchy) look duplicate.',
                'expectation' => 'Three clear models or hide unused Agents until CRUD is complete.',
                'solution' => 'Keep files; document: Agents = franchise children; Team = login users; Sub-merchants = admin tree. Hide Agents from nav if unused.',
            ],
            [
                'id' => 'PNL-ST01',
                'title' => 'Staff cannot see partner keys (correct)',
                'problem' => 'None — intentional exclusion from staff nav.',
                'expectation' => 'Support/ops work without Registry secrets.',
                'solution' => 'Keep. Add Payment Links/QR to staff nav without adding Registry.',
            ],
            [
                'id' => 'PNL-ST02',
                'title' => 'admin_risk_engine allows phantom role risk',
                'problem' => 'requireStaffAccess includes role risk which is not in staffRoleDefinitions.',
                'expectation' => 'Allowed roles ⊆ defined roles.',
                'solution' => 'Remove dead risk role or add real Risk role + nav; prefer map to ops/finance.',
            ],
            [
                'id' => 'PNL-ST03',
                'title' => 'Risk surfaces split across three pages',
                'problem' => 'admin_risk.php, admin_aml.php, admin_risk_engine.php overlap in mental model.',
                'expectation' => 'One Risk hub with Rules / Flags / Engine.',
                'solution' => 'Keep code; add hub links or tabs; rename staff nav Risk & AML accordingly.',
            ],
            [
                'id' => 'PNL-C01',
                'title' => 'Customer panel scope is correct',
                'problem' => 'No global search; no wallet — some owners may ask for both.',
                'expectation' => 'Customer = OTP login, history, complaints, profile. No PPI.',
                'solution' => 'Keep. Optional later: customer-scoped ticket/txn search only.',
            ],
            [
                'id' => 'PNL-PUB01',
                'title' => 'Public legal pack present',
                'problem' => 'Blog may be empty until seeded; contact needs SMTP.',
                'expectation' => 'Filled legal + working contact ticket path.',
                'solution' => 'Verify blog_posts on live; SMTP for contact mail; ensure DB ticket even if mail fails.',
            ],
        ],
    ],
    [
        'title' => '4 · Duplicate pages & functions (keep / merge / hide)',
        'intro' => 'Same job twice confuses merchants and staff. Decision per pair.',
        'items' => [
            [
                'id' => 'DUP-01',
                'title' => 'wallet.php vs settlements.php',
                'problem' => 'Both settlement-related; shared icon.',
                'expectation' => 'Balance vs settlement history clearly split.',
                'solution' => 'KEEP BOTH. Distinct icons; nav Settlement Balance vs Settlements.',
            ],
            [
                'id' => 'DUP-02',
                'title' => 'payment_methods.php vs collection_settings.php',
                'problem' => 'Method toggles may dual-write from collection settings.',
                'expectation' => 'Methods page = ON/OFF; collection = mode/rail only.',
                'solution' => 'KEEP BOTH; remove leftover method save from collection_settings if still dual-writing.',
            ],
            [
                'id' => 'DUP-03',
                'title' => 'admin_reports.php vs admin_financial_reports.php',
                'problem' => 'Two admin report homes.',
                'expectation' => 'One Reports entry.',
                'solution' => 'MERGE UX: keep financial date-range as primary; redirect the other or make a tab.',
            ],
            [
                'id' => 'DUP-04',
                'title' => 'admin_transaction_monitor.php vs admin_throughput.php',
                'problem' => 'Both show TPS-style monitoring.',
                'expectation' => 'One live ops monitor.',
                'solution' => 'MERGE: keep richer transaction_monitor; redirect throughput into it.',
            ],
            [
                'id' => 'DUP-05',
                'title' => 'disputes.php vs chargebacks.php',
                'problem' => 'Chargebacks UI title says Disputes & chargebacks.',
                'expectation' => 'Clear labels for two flows.',
                'solution' => 'KEEP BOTH; fix H2 to Chargebacks only.',
            ],
            [
                'id' => 'DUP-06',
                'title' => 'gateway_settings.php vs admin_gateway_registry.php',
                'problem' => 'Look like two key places.',
                'expectation' => 'Registry = partners/keys; Platform = SMTP/ops.',
                'solution' => 'KEEP BOTH with banners that point keys to Registry only.',
            ],
            [
                'id' => 'DUP-07',
                'title' => 'qr_code.php vs qr_upi_print.php',
                'problem' => 'Two QR products; Instant UPI may bypass UniWeb settlement.',
                'expectation' => 'Distinct purpose + honest warning.',
                'solution' => 'KEEP BOTH; Instant UPI banner must say money may not hit UniWeb ledger.',
            ],
            [
                'id' => 'DUP-08',
                'title' => 'cust.php and payer.php both → customer login',
                'problem' => 'Two short URLs same job.',
                'expectation' => 'Documented short links OK.',
                'solution' => 'KEEP BOTH; pick one for public docs.',
            ],
            [
                'id' => 'DUP-09',
                'title' => 'admin_wallet.php vs admin_platform_wallet.php',
                'problem' => 'Related money screens.',
                'expectation' => 'Bank withdraw vs fee ledger titles stay clear.',
                'solution' => 'KEEP BOTH; cross-link headers.',
            ],
            [
                'id' => 'DUP-10',
                'title' => 'security.php vs merchant_2fa.php',
                'problem' => 'Password vs TOTP split.',
                'expectation' => 'OK split under Settings hub.',
                'solution' => 'KEEP BOTH.',
            ],
        ],
    ],
    [
        'title' => '5 · Global search (must become universal)',
        'intro' => 'Owner requirement: every feature and every important data row reachable from the search bar (admin/merchant/staff).',
        'items' => [
            [
                'id' => 'SRCH-01',
                'title' => 'Payment Links / QR page-jump broken for admin aliases',
                'problem' => 'Aliases map to admin_payment_links.php / admin_qr_codes.php but those URLs are not in uniwebAdminSearchPages, so Page results never appear.',
                'expectation' => 'Typing payment links or QR jumps to the admin list pages.',
                'solution' => 'Add both URLs to admin nav + search page list, or allow aliases without membership check for super.',
            ],
            [
                'id' => 'SRCH-02',
                'title' => 'Missing record types in search',
                'problem' => 'No free-text search for orders, chargebacks, beneficiaries, packs, bank accounts, payouts, method requests, VAs, AML flags, admin invoices.',
                'expectation' => 'At least ORD / chargeback / pack / beneficiary / payout findable; exact IDs via id_go.',
                'solution' => 'Extend global_search.php loops + result links; keep role gates.',
            ],
            [
                'id' => 'SRCH-03',
                'title' => 'Feature aliases incomplete for Advanced tools',
                'problem' => 'Nickname search (MDR, cron, 2FA, encrypt PII, watchdog) is thin.',
                'expectation' => 'Common ops nicknames hit the right page.',
                'solution' => 'Expand $featureAliases in global_search.php / sidebar helpers.',
            ],
            [
                'id' => 'SRCH-04',
                'title' => 'Staff search returns rows for pages they cannot open',
                'problem' => 'Some admin record queries run without canPage gates.',
                'expectation' => 'Either gate queries or soft-fail open with permission flash.',
                'solution' => 'Wrap loops in staffCanAccess / canPage checks.',
            ],
            [
                'id' => 'SRCH-05',
                'title' => 'Customer portal has no search bar',
                'problem' => 'global_search_ui only in merchant/admin/staff header.',
                'expectation' => 'Optional customer-scoped search for own TXN/ticket.',
                'solution' => 'Later: customer-only search; not required for PPI-free scope.',
            ],
            [
                'id' => 'SRCH-06',
                'title' => '100% coverage target',
                'problem' => 'Owner asked A–Z everything searchable.',
                'expectation' => 'Every nav URL + every primary money/KYC/staff/settings entity.',
                'solution' => 'Treat as Phase 6 program: (1) page jump complete (2) money entities (3) KYC/staff (4) settings nicknames (5) ID hop parity with id_click.php.',
            ],
        ],
    ],
    [
        'title' => '6 · Market research & peer comparison',
        'intro' => 'Peers: Juspay, Cashfree, Razorpay, Stripe, Worldline, PayU, Decentro. Reference only — do not clone catalogues before Phase 0–2 live green.',
        'items' => [
            [
                'id' => 'P9-01',
                'title' => 'Professional polish vs Razorpay / Cashfree marketing',
                'problem' => 'Empty tables, raw errors, and unclear Test/Live cues feel unfinished.',
                'expectation' => 'Educated empty states; actionable errors; Test never looks like live money.',
                'solution' => 'Phase 8 empty states + userFacingError; Owner live smoke on collect path.',
            ],
            [
                'id' => 'P9-02',
                'title' => 'Collections reliability bar',
                'problem' => 'Merchants judge create link → pay → settle and print QR → scan.',
                'expectation' => 'Same reliability as Razorpay Links/QR for the happy path.',
                'solution' => 'Owner click-check checkout, QR PNG, share URL; Partner Registry keys only.',
            ],
            [
                'id' => 'P9-03',
                'title' => 'Docs / webhooks vs Stripe',
                'problem' => 'Thin docs look amateur even if UI works.',
                'expectation' => 'API docs, HMAC verify, delivery log, strict test keys.',
                'solution' => 'Keep api_docs.php; deepen when a deal asks; never settle live in Test.',
            ],
            [
                'id' => 'P9-04',
                'title' => 'Do not claim Juspay-style orchestration',
                'problem' => 'Orchestrator marketing without multi-rail uptime is empty.',
                'expectation' => 'Honest status page + partner routing story.',
                'solution' => 'status.php + Watchdog green; no second orchestrator app.',
            ],
            [
                'id' => 'P9-05',
                'title' => 'Payouts / Easy Split vs Cashfree',
                'problem' => 'Payouts scaffold; Route/Easy Split not live.',
                'expectation' => 'Collect first; payouts after keys; no fake marketplace split.',
                'solution' => 'Honest payout UI; park Route (P11) until Owner + commercial.',
            ],
            [
                'id' => 'P9-06',
                'title' => 'Coverage honesty vs PayU / Worldline',
                'problem' => 'Showing card/POS without credentials looks fake.',
                'expectation' => 'Only enabled methods show as available.',
                'solution' => 'Hard-gate methods on Partner Registry + merchant activation; POS only if a real deal.',
            ],
            [
                'id' => 'P9-07',
                'title' => 'Decentro is a partner, not UniWeb-as-bank',
                'problem' => 'Blurring brands / staging-as-live destroys trust.',
                'expectation' => 'Sandbox vs production always labelled.',
                'solution' => 'Keys on Partner Detail; environment selectors; UniWeb = merchant console.',
            ],
            [
                'id' => 'P9-08',
                'title' => 'Licence language',
                'problem' => 'Over-claiming RBI PA or 0% UPI forever is legal risk.',
                'expectation' => 'Honest trust centre; live money via contracted partners.',
                'solution' => 'Keep trust.php factual; never claim independent PA/banking licence unless true.',
            ],
        ],
    ],
    [
        'title' => '7 · White-label buyer requirements',
        'intro' => 'What a bank/fintech may demand. Implement a row only if Owner names a deal — after Phase 0–2. Do not put Buy white-label on homepage.',
        'items' => [
            [
                'id' => 'WL-01',
                'title' => 'Branding / domain',
                'problem' => 'Buyers want logo + often custom domain; UniWeb is one Hostinger APP_URL.',
                'expectation' => 'Checkout brandable; domain via Hostinger when deal requires.',
                'solution' => 'Use Checkout Customize today; deal domain = Hostinger SSL + APP_URL. No *_v2 app.',
            ],
            [
                'id' => 'WL-07',
                'title' => 'Programmatic merchant onboarding API',
                'problem' => 'Banks want REST create-merchant / KYC status.',
                'expectation' => 'Documented API or written exception (UI-only onboarding).',
                'solution' => 'Park until deal; then extend api_docs.php. Until then: signup + invite + KYC UI.',
            ],
            [
                'id' => 'WL-09',
                'title' => 'PCI / security questionnaire pack',
                'problem' => 'Fake PCI Level 1 badges destroy diligence.',
                'expectation' => 'Honest answers mapped to trust controls.',
                'solution' => 'Map questionnaires to trust.php; never invent certifications.',
            ],
            [
                'id' => 'WL-13',
                'title' => 'Multi-MID / multi-acquirer matrix',
                'problem' => 'Enterprise wants clear MID ↔ partner rail matrix.',
                'expectation' => 'Ops can explain which rail each merchant uses.',
                'solution' => 'Partner Registry + methods matrix; deep multi-MID UI only if deal needs.',
            ],
            [
                'id' => 'WL-14',
                'title' => 'Maker-checker dual control',
                'problem' => 'Roles exist; full dual-approve product is thin.',
                'expectation' => 'Sensitive money/go-live needs second approver when contract requires.',
                'solution' => 'Interim: staff roles + audit log; build dual-approve only for named deal.',
            ],
            [
                'id' => 'WL-15',
                'title' => 'Full portal white-label shell',
                'problem' => 'Checkout brandable; full dashboard still UniWeb chrome.',
                'expectation' => 'Portal chrome matches buyer when deal requires.',
                'solution' => 'Config flags for logo/name; avoid second codebase.',
            ],
            [
                'id' => 'WL-EXIST',
                'title' => 'Already largely present for buyers',
                'problem' => 'Buyers may not know what UniWeb already has.',
                'expectation' => 'Checklist of existing WL strengths.',
                'solution' => 'HAVE: hide powered-by option, Test/Live isolation, HMAC webhooks+retry, RBAC without keys, CSV reports, status page, disputes timers, recon upload, audit CSV, API docs scaffold.',
            ],
        ],
    ],
    [
        'title' => '8 · Owner live verification checklist (Block E style)',
        'items' => [
            [
                'id' => 'LIVE-01',
                'title' => 'After every Git pull',
                'problem' => 'Code on GitHub is not live until Hostinger pulls.',
                'expectation' => 'Pull → hard refresh → smoke.',
                'solution' => 'Smoke: home, merchant login, Payment Links (methods + Fixed/Open), Payment Pack Regenerate, checkout Instant Test Pay, admin dashboard, KYC decrypt view.',
            ],
            [
                'id' => 'LIVE-02',
                'title' => 'Migrations & PII',
                'problem' => 'Schema/cipher width may lag code.',
                'expectation' => 'Apply pending migrations (062/063); Encrypt PII backfill if plaintext remains.',
                'solution' => 'Admin Apply pending migrations; Encrypt PII Backfill; never DROP DATABASE.',
            ],
            [
                'id' => 'LIVE-03',
                'title' => 'Backup before Hostinger cleanup deletes',
                'problem' => 'Block A file deletes without backup risk the site.',
                'expectation' => 'Files Backups + SQL export first.',
                'solution' => 'Follow BLOCK_A_CLEANUP.md; delete only zip/tests/dev_local junk.',
            ],
        ],
    ],
];
